name: human-parse
version: 0.1.0.3
category: Text

synopsis: >
  A lawless typeclass for parsing text entered by humans.

description: >
  An unprincipled best-effort informal attempt to figure out what a human is
  saying.

library:
  source-dirs: src
  exposed-modules:
    - Data.Text.Human.Parse

author:     Chris Martin <ch.martin@gmail.com>
maintainer: Chris Martin <ch.martin@gmail.com>

homepage: https://github.com/chris-martin/human

license:      Apache-2.0
license-file: license.txt

dependencies:
  - base >= 4.9 && < 4.11
  - text

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
